// Generated by https://quicktype.io

export interface Auth {
    message: string;
    token:   string;
    data:    User;
}

export interface User {
    id:     number;
    nombre: string;
    correo: string;
    estado: number;
}
